### ISSUE TITLE
First run, nginx.tmpl is created as a directory instead of a file

### ISSUE THREAD

**Issue by emcniece** [Munsio/docker-letsencrypt-nginx-proxy-companion#3]
When I first run this stack, `nginx.tmpl` gets created but it is a directory instead of a file. The nginx-gen container then throws errors during startup because it cannot read this file (which isn't a file).

docker-compose.yml:

```yml
version: '2'
services:
  nginx:
    image: "nginx"
    tty: true
    stdin_open: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DIR}/conf.d:/etc/nginx/conf.d
      - ${DIR}/vhost.d:/etc/nginx/vhost.d
      - ${DIR}/html:/usr/share/nginx/html
      - ${DIR}/certs:/etc/nginx/certs:ro
    labels:
      io.rancher.scheduler.global: 'true'
  nginx-gen:
    image: "jwilder/docker-gen"
    tty: true
    stdin_open: true
    volumes:
      - ${DIR}/conf.d:/etc/nginx/conf.d
      - ${DIR}/vhost.d:/etc/nginx/vhost.d
      - ${DIR}/html:/usr/share/nginx/html
      - ${DIR}/certs:/etc/nginx/certs:ro
      - ${DIR}/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${SOCKET}:/tmp/docker.sock:ro
    links:
      - nginx
    command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    tty: true
    stdin_open: true
    links:
      - nginx
    volumes_from:
      - nginx
    labels:
      io.rancher.sidekicks: nginx
    volumes:
      - ${DIR}/conf.d:/etc/nginx/conf.d
      - ${DIR}/vhost.d:/etc/nginx/vhost.d
      - ${DIR}/html:/usr/share/nginx/html
      - ${DIR}/certs:/etc/nginx/certs:rw
      - ${SOCKET}:/var/run/docker.sock:ro
```
